name: Panorama Build

on:
  push:
    branches: [ 1.20 ]
    paths:
      - 'src/**'
  pull_request:
    branches: [ 1.20 ]
    paths:
      - 'src/**'

env:
  JDK_VERSION: 17
	  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ env.JDK_VERSION }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: ./build/libs/*.jar
